/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.DaoCategoria;
import controlador.DaoEntradas;
import controlador.DaoProductos;
import controlador.DaoProveedor;
import java.util.Calendar;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Categoria;
import modelo.entradas;
import modelo.productos;
import modelo.proveedor;

/**
 *
 * @author User
 */
public class Entradas extends javax.swing.JPanel {

     entradas e=new entradas();
     productos p=new productos();
     DaoEntradas DaoE=new DaoEntradas();
     DefaultTableModel modeloE = new DefaultTableModel();
     DaoCategoria cat=new DaoCategoria();
     DaoProveedor pro=new DaoProveedor();
     DaoProductos DaoP=new DaoProductos();
     Categoria ct= new Categoria();
     proveedor pr=new proveedor();
    /**
     * Creates new form Entradas
     */
    public Entradas(){
        initComponents();
        listarEntrada();
    }

    
  private void listarEntrada(){
 List<entradas> listaEntrada = DaoE.listarEntradas();
modeloE = (DefaultTableModel) TablaE.getModel();
  modeloE.setRowCount(0);

Object[] ob = new Object[9];
for (int i = 0; i < listaEntrada.size(); i++) {
    ob[0] = listaEntrada.get(i).getIdEntrada();
    ob[1] = listaEntrada.get(i).getNomProd();
    ob[2] = listaEntrada.get(i).getStock();
    ob[3] = listaEntrada.get(i).getIdCategoria();
    ob[4] = listaEntrada.get(i).getFecha();
    ob[5] = listaEntrada.get(i).getIdProveedor();
    ob[6] = listaEntrada.get(i).getPrecioE();
    ob[7] = listaEntrada.get(i).getPrecioV();
    ob[8] = listaEntrada.get(i).getTotal();
    modeloE.addRow(ob);
    }
  }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpanelRound1 = new modelo.JpanelRound();
        jLabel2 = new javax.swing.JLabel();
        txtIdE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreProductoE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrecioE = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecioVE = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTotalE = new javax.swing.JTextField();
        DateFecha = new com.toedter.calendar.JDateChooser();
        jpanelRound2 = new modelo.JpanelRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtidCat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtCat = new javax.swing.JTextField();
        btnBuscarCategoria = new RSMaterialComponent.RSButtonMaterialIconDos();
        jpanelRound3 = new modelo.JpanelRound();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnBuscaPro = new RSMaterialComponent.RSButtonMaterialIconDos();
        txtidPro = new javax.swing.JTextField();
        txtNombrePro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaE = new javax.swing.JTable();
        BtnGuardarE = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEditarE = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEliminarE = new RSMaterialComponent.RSButtonMaterialIconDos();
        BtnBuscarE = new RSMaterialComponent.RSButtonMaterialIconDos();
        jpanelRound4 = new modelo.JpanelRound();
        jLabel15 = new javax.swing.JLabel();
        btnBuscarProducto = new RSMaterialComponent.RSButtonMaterialIconDos();
        jLabel16 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setText("Registro de Entradas");

        jpanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound1.setRoundBottomLeft(25);
        jpanelRound1.setRoundBottomRight(25);
        jpanelRound1.setRoundTopLeft(25);
        jpanelRound1.setRoundTopRight(25);

        jLabel2.setText("ID Entrada");

        jLabel3.setText("Nombre del producto");

        txtNombreProductoE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoEActionPerformed(evt);
            }
        });

        jLabel4.setText("Stock");

        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStockKeyReleased(evt);
            }
        });

        jLabel5.setText("Fecha");

        jLabel6.setText("Precio Entrada");

        txtPrecioE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioEActionPerformed(evt);
            }
        });
        txtPrecioE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioEKeyReleased(evt);
            }
        });

        jLabel7.setText("Precio Venta");

        txtPrecioVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioVEActionPerformed(evt);
            }
        });

        jLabel8.setText("Total");

        javax.swing.GroupLayout jpanelRound1Layout = new javax.swing.GroupLayout(jpanelRound1);
        jpanelRound1.setLayout(jpanelRound1Layout);
        jpanelRound1Layout.setHorizontalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(txtIdE)
                    .addComponent(txtNombreProductoE)
                    .addComponent(txtStock)
                    .addComponent(txtPrecioE)
                    .addComponent(txtPrecioVE)
                    .addComponent(txtTotalE)
                    .addComponent(DateFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jpanelRound1Layout.setVerticalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreProductoE, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecioE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioVE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotalE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jpanelRound2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel10.setText("Datos de Categoria");

        jLabel13.setText("ID");

        jLabel14.setText("Categoria");

        txtCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCatActionPerformed(evt);
            }
        });

        btnBuscarCategoria.setText("buscar");
        btnBuscarCategoria.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        btnBuscarCategoria.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelRound2Layout = new javax.swing.GroupLayout(jpanelRound2);
        jpanelRound2.setLayout(jpanelRound2Layout);
        jpanelRound2Layout.setHorizontalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(btnBuscarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(txtCat, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(txtidCat))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpanelRound2Layout.setVerticalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(btnBuscarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jpanelRound3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel9.setText("Datos de proveedor");

        jLabel11.setText("ID");

        jLabel12.setText("Nombre");

        btnBuscaPro.setText("buscar");
        btnBuscaPro.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        btnBuscaPro.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscaPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaProActionPerformed(evt);
            }
        });

        txtNombrePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelRound3Layout = new javax.swing.GroupLayout(jpanelRound3);
        jpanelRound3.setLayout(jpanelRound3Layout);
        jpanelRound3Layout.setHorizontalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelRound3Layout.createSequentialGroup()
                        .addGroup(jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addContainerGap(189, Short.MAX_VALUE))
                    .addGroup(jpanelRound3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(jpanelRound3Layout.createSequentialGroup()
                        .addGroup(jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNombrePro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(txtidPro, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpanelRound3Layout.setVerticalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnBuscaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtidPro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TablaE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Producto", "Stock", "IDCategoria", "Fecha", "IDProveedor", "Precio E", "Precio V", "Total"
            }
        ));
        TablaE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaE);

        BtnGuardarE.setBackground(new java.awt.Color(255, 0, 51));
        BtnGuardarE.setText("Guardar");
        BtnGuardarE.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        BtnGuardarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarEActionPerformed(evt);
            }
        });

        btnEditarE.setBackground(new java.awt.Color(51, 102, 255));
        btnEditarE.setText("Editar");
        btnEditarE.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarEActionPerformed(evt);
            }
        });

        btnEliminarE.setBackground(new java.awt.Color(51, 102, 255));
        btnEliminarE.setText("Eliminar");
        btnEliminarE.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnEliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEActionPerformed(evt);
            }
        });

        BtnBuscarE.setBackground(new java.awt.Color(51, 102, 255));
        BtnBuscarE.setText("Buscar");
        BtnBuscarE.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        BtnBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarEActionPerformed(evt);
            }
        });

        jpanelRound4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel15.setText("Buscar Producto");

        btnBuscarProducto.setText("buscar");
        btnBuscarProducto.setFont(new java.awt.Font("Roboto Bold", 1, 12)); // NOI18N
        btnBuscarProducto.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        jLabel16.setText("ID  Producto");

        javax.swing.GroupLayout jpanelRound4Layout = new javax.swing.GroupLayout(jpanelRound4);
        jpanelRound4.setLayout(jpanelRound4Layout);
        jpanelRound4Layout.setHorizontalGroup(
            jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelRound4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelRound4Layout.setVerticalGroup(
            jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jpanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jpanelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpanelRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jpanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(BtnGuardarE, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnEditarE, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnGuardarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jpanelRound2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpanelRound3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpanelRound4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBuscarE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProductoEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoEActionPerformed

    private void txtPrecioEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioEActionPerformed

    private void txtPrecioVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVEActionPerformed

    private void txtCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCatActionPerformed

    private void btnEditarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarEActionPerformed
        // TODO add your handling code here:
             
        int file=TablaE.getSelectedRow();
         if (file ==-1){
             JOptionPane.showMessageDialog(null,"seleccione una entrada");
         }else if (txtIdE.getText().isEmpty()) {
              JOptionPane.showMessageDialog(null, "Seleccione una categoría");
             
         }else{
             Calendar cal;
        int d,m,a;
        cal=DateFecha.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR)-1900;
        
       e.setNomProd(txtNombreProductoE.getText());
       e.setStock(Integer.parseInt(txtStock.getText()));
       e.setIdCategoria(Integer.parseInt(txtidCat.getText()));
       e.setFecha(new Date(a,m,d));
       e.setIdProveedor(Integer.parseInt(txtidPro.getText()));
       e.setPrecioE(Double.parseDouble(txtPrecioE.getText()));
       e.setPrecioV(Double.parseDouble(txtPrecioVE.getText()));
       e.setTotal(Double.parseDouble(txtTotalE.getText()));
       e.setIdEntrada(Integer.parseInt(txtIdE.getText()));
       
       if(DaoE.editar(e)){
             //JOptionPane.showMessageDialog(null,"se modifico con exito");
              MenuPrincipal m1 =new MenuPrincipal(); 
              m1.exito("modificado con exito");
             limpiarCampos();
             limpiarTablaEntradas();
             listarEntrada();
           }else{
           MenuPrincipal m2 =new MenuPrincipal(); 
              m2.exito("Error al modificar la entrada");
             }
         }
    }//GEN-LAST:event_btnEditarEActionPerformed

    private void BtnGuardarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarEActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Calendar cal;
        int d,m,a;
        cal=DateFecha.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR)-1900;
        
       e.setNomProd(txtNombreProductoE.getText());
       e.setStock(Integer.parseInt(txtStock.getText()));
       e.setIdCategoria(Integer.parseInt(txtidCat.getText()));
       e.setFecha(new Date(a,m,d));
       e.setIdProveedor(Integer.parseInt(txtidPro.getText()));
       e.setPrecioE(Double.parseDouble(txtPrecioE.getText()));
       e.setPrecioV(Double.parseDouble(txtPrecioVE.getText()));
       e.setTotal(Double.parseDouble(txtTotalE.getText()));
       
       p.setNomProd(txtNombreProductoE.getText());
       p.setStock(Integer.parseInt(txtStock.getText()));
       p.setIdCategoria(Integer.parseInt(txtidCat.getText()));
       
       p.setFecha(new Date(a,m,d));
       p.setIdproveedor(Integer.parseInt(txtidPro.getText()));
       p.setPrecioV(Double.parseDouble(txtPrecioVE.getText()));
   
       if(DaoE.insertar(e)){
          // JOptionPane.showMessageDialog(null, "Registro de categoría completado");
           MenuPrincipal me =new MenuPrincipal(); 
           me.exito("la entrada ha sido registrada con exito");
           limpiarCampos();
           limpiarTablaEntradas();
           listarEntrada();
           
       }else{
           MenuPrincipal me =new MenuPrincipal(); 
           me.warning("No se pudo registrar la entrada");
       }             
       
        
    }//GEN-LAST:event_BtnGuardarEActionPerformed

    private void txtPrecioEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioEKeyReleased
        // TODO add your handling code here:
        double cant,precio;
    if (!txtStock.getText().isEmpty()) {
        cant=Double.parseDouble(txtStock.getText());
        precio=Double.parseDouble(txtPrecioE.getText());
        txtTotalE.setText(cant*precio+"");
      }
    }//GEN-LAST:event_txtPrecioEKeyReleased

    private void btnBuscarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCategoriaActionPerformed
        // TODO add your handling code here:
    BuscarDatos.tipo=true;
         BuscarDatos me=new BuscarDatos();
            me.setVisible(true);
            
    }//GEN-LAST:event_btnBuscarCategoriaActionPerformed

    private void TablaEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEMouseClicked

        int fila = TablaE.getSelectedRow();
        txtIdE.setText(TablaE.getValueAt(fila, 0).toString());
        txtNombreProductoE.setText(TablaE.getValueAt(fila, 1).toString());
        txtStock.setText(TablaE.getValueAt(fila, 2).toString());
        txtidCat.setText(TablaE.getValueAt(fila, 3).toString());
        DateFecha.setDate(Date.valueOf(TablaE.getValueAt(fila,4).toString()));
        txtidPro.setText(TablaE.getValueAt(fila, 5).toString());
        txtPrecioE.setText(TablaE.getValueAt(fila, 6).toString()); 
        txtPrecioVE.setText(TablaE.getValueAt(fila, 7).toString());
        txtTotalE.setText(TablaE.getValueAt(fila, 8).toString());
        
        ct.setIdCategoria(Integer.parseInt(txtidCat.getText()));
       if(cat.buscar(ct)){
          txtCat.setText(ct.getNomCategoria());
       }else{
          txtCat.setText("Error");
       }    
       
       pr.setIdProveedor(Integer.parseInt(txtidPro.getText()));
       if(pro.buscar(pr)){
          txtNombrePro.setText(pr.getNombre());
       }else{
          txtNombrePro.setText("Error");
       }    
       
    }//GEN-LAST:event_TablaEMouseClicked

    private void btnBuscaProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaProActionPerformed
        // TODO add your handling code here:
        BuscarDatos.tipo=false;
         BuscarDatos me=new BuscarDatos();
            me.setVisible(true);
    }//GEN-LAST:event_btnBuscaProActionPerformed

    private void txtNombreProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProActionPerformed

    private void btnEliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        if (!txtIdE.getText().isEmpty()) {
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿De verdad Estas seguro de eliminar la entrada?", "Confirmar", 2);
        if (confirmacion == 0) {
            e.setIdEntrada(Integer.parseInt(txtIdE.getText()));
            DaoE.eliminar(e);
             limpiarCampos();
             limpiarTablaEntradas();
             listarEntrada();
            //JOptionPane.showMessageDialog(null, "Se elimino con exito el cliente");
             MenuPrincipal me =new MenuPrincipal(); 
             me.exito("Se elimino con exito");
         }
      }else{
            MenuPrincipal me =new MenuPrincipal(); 
             me.warning("Seleccione una Entrada");
        }
        
    }//GEN-LAST:event_btnEliminarEActionPerformed

    private void txtStockKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyReleased
        // TODO add your handling code here:
        double cant,precio;
    if (!txtPrecioE.getText().isEmpty()) {
        cant=Double.parseDouble(txtStock.getText());
        precio=Double.parseDouble(txtPrecioE.getText());
        txtTotalE.setText(cant*precio+"");
      }
    }//GEN-LAST:event_txtStockKeyReleased

    private void BtnBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarEActionPerformed
        // TODO add your handling code here:
        
              e.setIdEntrada(Integer.parseInt(txtIdE.getText()));
              if (DaoE.buscar(e)){
                txtIdE.setText(e.getIdEntrada()+"");
                txtidCat.setText(e.getIdCategoria()+"");
                txtNombreProductoE.setText(e.getNomProd());
                txtStock.setText(e.getStock()+"");
                txtPrecioE.setText(e.getPrecioE()+"");
                txtPrecioVE.setText(e.getPrecioV()+"");
                txtTotalE.setText(e.getTotal()+"");
                txtidCat.setText(e.getIdCategoria()+"");
                txtCat.setText("");
                txtidPro.setText(e.getIdProveedor()+"");
                txtNombrePro.setText("");
                ct.setIdCategoria(Integer.parseInt(txtidCat.getText()));
                 if(cat.buscar(ct)){
                   txtCat.setText(ct.getNomCategoria());
                 }else{
                   txtCat.setText("Error");
                  }    
                pr.setIdProveedor(Integer.parseInt(txtidPro.getText()));
               
                 if(pro.buscar(pr)){
                     txtNombrePro.setText(pr.getNombre());
                 }else{
                    txtNombrePro.setText("Error");
                   }    
               } else {         
                MenuPrincipal me =new MenuPrincipal(); 
                me.warning("la entrada no existe");
                limpiarCampos();
             }
    }//GEN-LAST:event_BtnBuscarEActionPerformed

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    
    void limpiarCampos(){
     txtIdE.setText("");
     txtidCat.setText("");
     txtNombreProductoE.setText("");
     txtStock.setText("");
     txtPrecioE.setText("");
     txtPrecioVE.setText("");
     txtTotalE.setText("");
     txtidCat.setText("");
     txtCat.setText("");
     txtidPro.setText("");
     txtNombrePro.setText("");
 }

  void limpiarTablaEntradas(){
          for (int i = 0; i < modeloE.getRowCount(); i++) {
        modeloE.removeRow(i);
        i = i - 1;
       }
     }
             


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos BtnBuscarE;
    private RSMaterialComponent.RSButtonMaterialIconDos BtnGuardarE;
    private com.toedter.calendar.JDateChooser DateFecha;
    private javax.swing.JTable TablaE;
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscaPro;
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscarCategoria;
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscarProducto;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEditarE;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEliminarE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private modelo.JpanelRound jpanelRound1;
    private modelo.JpanelRound jpanelRound2;
    private modelo.JpanelRound jpanelRound3;
    private modelo.JpanelRound jpanelRound4;
    public static javax.swing.JTextField txtCat;
    private javax.swing.JTextField txtIdE;
    public static javax.swing.JTextField txtNombrePro;
    private javax.swing.JTextField txtNombreProductoE;
    private javax.swing.JTextField txtPrecioE;
    private javax.swing.JTextField txtPrecioVE;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTotalE;
    public static javax.swing.JTextField txtidCat;
    public static javax.swing.JTextField txtidPro;
    // End of variables declaration//GEN-END:variables
}
