/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;


import controlador.DaoProveedor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.proveedor;


/**
 *
 * @author User
 */
public class Proveedores extends javax.swing.JPanel {

    proveedor pro=new proveedor();
    DaoProveedor ctp=new DaoProveedor();
    DefaultTableModel modeloPro =new DefaultTableModel();
    
    /**
     * Creates new form Proovedores
     */
    public Proveedores() {
        initComponents();
        listarProveedores();
    }

  private void listarProveedores() {
 List<proveedor> listaProveedores = ctp.listarProveedor();
modeloPro = (DefaultTableModel) tablaProv.getModel();
Object[] ob = new Object[8];  // Arreglo de 7 elementos

for (int i = 0; i < listaProveedores.size(); i++) {
    // Obtener los datos de cada cliente de la lista
    ob[0] = listaProveedores.get(i).getIdProveedor();
    ob[1] = listaProveedores.get(i).getNombre();
    ob[2] = listaProveedores.get(i).getApellido();
    ob[3] = listaProveedores.get(i).getDocumento();
    ob[4] = listaProveedores.get(i).getRazonS();
    ob[5] = listaProveedores.get(i).getDireccion();
    ob[6] = listaProveedores.get(i).getTelefono();
    ob[7] = listaProveedores.get(i).getCorreo();

    // Añadir la fila con los datos del cliente
    modeloPro.addRow(ob);
   }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpanelRound1 = new modelo.JpanelRound();
        jLabel2 = new javax.swing.JLabel();
        txtIdP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRazonP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDireccionP = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefonoP = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCorreoP = new javax.swing.JTextField();
        txtDocumentoP = new javax.swing.JTextField();
        jpanelRound4 = new modelo.JpanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProv = new javax.swing.JTable();
        btnGuardarP = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEditarP = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEliminarP = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnBuscarP = new RSMaterialComponent.RSButtonMaterialIconDos();

        setPreferredSize(new java.awt.Dimension(563, 624));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setText("Registro de Proveedores");

        jpanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound1.setRoundBottomLeft(25);
        jpanelRound1.setRoundBottomRight(25);
        jpanelRound1.setRoundTopLeft(25);
        jpanelRound1.setRoundTopRight(25);

        jLabel2.setText("ID");

        jLabel3.setText("Nombre");

        txtNombreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePActionPerformed(evt);
            }
        });

        jLabel4.setText("Apellido");

        jLabel5.setText("Documento");

        jLabel6.setText("Razon social");

        txtRazonP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRazonPActionPerformed(evt);
            }
        });
        txtRazonP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRazonPKeyReleased(evt);
            }
        });

        jLabel7.setText("Direccion");

        txtDireccionP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionPActionPerformed(evt);
            }
        });

        jLabel8.setText("Telefono");

        jLabel9.setText("Correo");

        txtDocumentoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoPActionPerformed(evt);
            }
        });
        txtDocumentoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDocumentoPKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jpanelRound1Layout = new javax.swing.GroupLayout(jpanelRound1);
        jpanelRound1.setLayout(jpanelRound1Layout);
        jpanelRound1Layout.setHorizontalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDocumentoP, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(txtCorreoP)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(txtIdP, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(txtNombreP)
                            .addComponent(txtApellidoP)
                            .addComponent(txtRazonP)
                            .addComponent(txtDireccionP)
                            .addComponent(txtTelefonoP))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jpanelRound1Layout.setVerticalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDocumentoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRazonP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDireccionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefonoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanelRound4.setBackground(new java.awt.Color(255, 255, 255));

        tablaProv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Documento", "Direccion", "Telefono", "Correo", "Razon Social"
            }
        ));
        tablaProv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProvMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProv);

        javax.swing.GroupLayout jpanelRound4Layout = new javax.swing.GroupLayout(jpanelRound4);
        jpanelRound4.setLayout(jpanelRound4Layout);
        jpanelRound4Layout.setHorizontalGroup(
            jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jpanelRound4Layout.setVerticalGroup(
            jpanelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        btnGuardarP.setBackground(new java.awt.Color(255, 0, 51));
        btnGuardarP.setText("Guardar");
        btnGuardarP.setBackgroundHover(new java.awt.Color(0, 112, 192));
        btnGuardarP.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPActionPerformed(evt);
            }
        });

        btnEditarP.setBackground(new java.awt.Color(51, 102, 255));
        btnEditarP.setText("Editar");
        btnEditarP.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPActionPerformed(evt);
            }
        });

        btnEliminarP.setBackground(new java.awt.Color(51, 102, 255));
        btnEliminarP.setText("Eliminar");
        btnEliminarP.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnEliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPActionPerformed(evt);
            }
        });

        btnBuscarP.setBackground(new java.awt.Color(51, 102, 255));
        btnBuscarP.setText("Buscar");
        btnBuscarP.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnGuardarP, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jpanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpanelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnEditarP, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanelRound4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePActionPerformed

    private void txtRazonPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRazonPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRazonPActionPerformed

    private void txtRazonPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRazonPKeyReleased
        // TODO add your handling code here:

        double cant,precio;
        cant=Double.parseDouble(txtApellidoP.getText());
        precio=Double.parseDouble(txtRazonP.getText());
        txtTelefonoP.setText(cant*precio+"");
    }//GEN-LAST:event_txtRazonPKeyReleased

    private void txtDireccionPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionPActionPerformed

    private void txtDocumentoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoPActionPerformed

    private void txtDocumentoPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoPKeyReleased

    private void tablaProvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProvMouseClicked
        // TODO add your handling code here:
        int fila = tablaProv.getSelectedRow();
        txtIdP.setText(tablaProv.getValueAt(fila, 0).toString());
        txtNombreP.setText(tablaProv.getValueAt(fila, 1).toString());
        txtApellidoP.setText(tablaProv.getValueAt(fila, 2).toString());
        txtDocumentoP.setText(tablaProv.getValueAt(fila, 3).toString());
        txtRazonP.setText(tablaProv.getValueAt(fila, 4).toString());
        txtDireccionP.setText(tablaProv.getValueAt(fila, 5).toString());
        txtTelefonoP.setText(tablaProv.getValueAt(fila, 6).toString());
        txtCorreoP.setText(tablaProv.getValueAt(fila, 7).toString()); 
    }//GEN-LAST:event_tablaProvMouseClicked

    private void btnGuardarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPActionPerformed
        // TODO add your handling code here:
           // TODO add your handling code here:
       pro.setNombre(txtNombreP.getText());
       pro.setApellido(txtApellidoP.getText());
       pro.setDocumento(txtDocumentoP.getText());
       pro.setRazonS(txtRazonP.getText());
       pro.setDireccion(txtDireccionP.getText());
       pro.setTelefono(txtTelefonoP.getText());
       pro.setCorreo(txtCorreoP.getText());
       if(ctp.insertar(pro)){
          // JOptionPane.showMessageDialog(null, "Registro de categoría completado");
           MenuPrincipal me =new MenuPrincipal(); 
           me.exito("proveedor registrado con exito");
           limpiarCampos();
           limpiarTablaProveedor();
           listarProveedores(); 
       }else{
           MenuPrincipal me =new MenuPrincipal(); 
           me.warning("Error al registrar Proveedor"); 
       }  
    }//GEN-LAST:event_btnGuardarPActionPerformed

    private void btnEditarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPActionPerformed
        // TODO add your handling code here:
           
       int fila = tablaProv.getSelectedRow();
        if (fila == -1 || txtIdP.getText().isEmpty()) {
         // JOptionPane.showMessageDialog(null, "Seleccione un Cliente");
            MenuPrincipal m = new MenuPrincipal();
                m.warning("Seleccione un Proveedor");
         }else{
             pro.setIdProveedor(Integer.parseInt(txtIdP.getText()));
             
             pro.setNombre(txtNombreP.getText());
             pro.setApellido(txtApellidoP.getText());
             pro.setDocumento(txtDocumentoP.getText());
             pro.setRazonS(txtRazonP.getText());
             pro.setDireccion(txtDireccionP.getText());
             pro.setTelefono(txtTelefonoP.getText());
             pro.setCorreo(txtCorreoP.getText());
             
             if(ctp.editar(pro)){
             //JOptionPane.showMessageDialog(null,"se modifico con exito");
              MenuPrincipal me =new MenuPrincipal(); 
              me.exito("modificado con exito");
             limpiarCampos();
             limpiarTablaProveedor();
             listarProveedores();
             }else{
              MenuPrincipal me =new MenuPrincipal(); 
              me.warning("Error al modificar el Proveedor"); 
             }
         }

    }//GEN-LAST:event_btnEditarPActionPerformed

    private void btnEliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPActionPerformed

          // TODO add your handling code here:
        if (!txtIdP.getText().isEmpty()) {
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿De verdad Estas seguro de eliminar el proovedor?", "Confirmar", 2);
        if (confirmacion == 0) {           
            pro.setIdProveedor(Integer.parseInt(txtIdP.getText()));
            ctp.eliminar(pro);
            limpiarTablaProveedor();
            listarProveedores();
            limpiarCampos();
            //JOptionPane.showMessageDialog(null, "Se elimino con exito el cliente");
             MenuPrincipal me =new MenuPrincipal(); 
             me.exito("Se elimino con exito");
         }
      }else{
          MenuPrincipal me =new MenuPrincipal(); 
          me.warning("Seleccione un proveedor");
        }
    }//GEN-LAST:event_btnEliminarPActionPerformed

    private void btnBuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPActionPerformed
        // TODO add your handling code here:
              pro.setDocumento(txtDocumentoP.getText());
              if (ctp.buscarDocumento(pro)){
                txtIdP .setText(pro.getIdProveedor()+"");
                txtNombreP.setText(pro.getNombre());
                txtApellidoP.setText(pro.getApellido());
                txtDocumentoP.setText(pro.getDocumento());
                txtRazonP.setText(pro.getRazonS());
                txtDireccionP.setText(pro.getDireccion());
                txtTelefonoP.setText(pro.getTelefono());
                txtCorreoP.setText(pro.getCorreo());
            } else {
              MenuPrincipal me =new MenuPrincipal(); 
              me.warning("El proveedor no existe"); 
              limpiarCampos();
             }

    }//GEN-LAST:event_btnBuscarPActionPerformed

    
    void limpiarCampos(){
     txtIdP.setText("");
     txtNombreP.setText("");
     txtApellidoP.setText("");
     txtDocumentoP.setText("");
     txtDireccionP.setText("");
     txtTelefonoP.setText("");
     txtCorreoP.setText("");
     txtRazonP.setText("");
 }

  void limpiarTablaProveedor(){
          for (int i = 0; i < modeloPro.getRowCount(); i++) {
        modeloPro.removeRow(i);
        i = i - 1;
       }
     }
             


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscarP;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEditarP;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEliminarP;
    private RSMaterialComponent.RSButtonMaterialIconDos btnGuardarP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private modelo.JpanelRound jpanelRound1;
    private modelo.JpanelRound jpanelRound4;
    private javax.swing.JTable tablaProv;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreoP;
    private javax.swing.JTextField txtDireccionP;
    private javax.swing.JTextField txtDocumentoP;
    private javax.swing.JTextField txtIdP;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtRazonP;
    private javax.swing.JTextField txtTelefonoP;
    // End of variables declaration//GEN-END:variables
}
