/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.DaoClientes;
import controlador.DaoDetaSalida;
import controlador.DaoSalidas;
import java.util.Calendar;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Clientes;
import modelo.salidas;

/**
 *
 * @author User
 */
public class Salidas extends javax.swing.JPanel {

    salidas s=new salidas();
    DaoSalidas Cts =new DaoSalidas();
    Clientes c=new Clientes();
    DaoClientes ctcl=new DaoClientes();
    DefaultTableModel modeloE = new DefaultTableModel();   
    DaoDetaSalida cdeta =new DaoDetaSalida();   
    /**
     * Creates new form Salidas
     */
    public Salidas() {
        initComponents();
        numSalida();
    }

    
    void numSalida(){
    String numero=Cts.numSalida();
    if(numero==null){
        txtnumSa.setText("001");
} else {
    int i = Integer.parseInt(numero);
    i = i + 1;
    txtnumSa.setText("00" + i);
}
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpanelRound1 = new modelo.JpanelRound();
        jLabel2 = new javax.swing.JLabel();
        txtDocumentoS = new javax.swing.JTextField();
        txtIDClienteS = new javax.swing.JTextField();
        txtTelefonoS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCorreoS = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNombreClienteS = new javax.swing.JTextField();
        jpanelRound2 = new modelo.JpanelRound();
        txtIDEntradaS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtProductoS = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtStockS = new javax.swing.JTextField();
        txtCantidadS = new javax.swing.JTextField();
        txtPrecioS = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JcFechaS = new com.toedter.calendar.JDateChooser();
        btnNuevaSa = new RSMaterialComponent.RSButtonMaterialIconDos();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaS = new javax.swing.JTable();
        jpanelRound3 = new modelo.JpanelRound();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        txtIGV = new javax.swing.JTextField();
        BtnGenerar = new RSMaterialComponent.RSButtonMaterialIconDos();
        txtTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        BtnAgregarEntrada = new RSMaterialComponent.RSButtonMaterialIconDos();
        BtnBuscarEntrada = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnBuscarCliente = new RSMaterialComponent.RSButtonMaterialIconDos();
        txtnumSa = new javax.swing.JLabel();
        txtnSalida = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setText("Registro de Salidas");

        jpanelRound1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Datos de Clientes");

        txtDocumentoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoSActionPerformed(evt);
            }
        });

        txtTelefonoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoSActionPerformed(evt);
            }
        });

        jLabel3.setText("Documento");

        jLabel4.setText("Telefono");

        jLabel5.setText("ID");

        jLabel6.setText("Correo");

        jLabel7.setText("Nombre");

        javax.swing.GroupLayout jpanelRound1Layout = new javax.swing.GroupLayout(jpanelRound1);
        jpanelRound1.setLayout(jpanelRound1Layout);
        jpanelRound1Layout.setHorizontalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8))
                    .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(jpanelRound1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(txtDocumentoS, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .addComponent(txtIDClienteS))
                                .addComponent(txtNombreClienteS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(55, 55, 55)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtCorreoS, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoS, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jpanelRound1Layout.setVerticalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpanelRound1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDocumentoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelRound1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCorreoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtIDClienteS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addGroup(jpanelRound1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefonoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreClienteS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpanelRound2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Datos del producto");

        jLabel10.setText("ID");

        jLabel11.setText("Nombre");

        jLabel12.setText("Stock disponible");

        jLabel13.setText("Cantidad");

        jLabel14.setText("Precio");

        jLabel8.setText("Fecha de Salida");

        btnNuevaSa.setBackground(new java.awt.Color(102, 255, 102));
        btnNuevaSa.setText("nueva salida");
        btnNuevaSa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaSaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelRound2Layout = new javax.swing.GroupLayout(jpanelRound2);
        jpanelRound2.setLayout(jpanelRound2Layout);
        jpanelRound2Layout.setHorizontalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9))
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11))
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtIDEntradaS, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                    .addGroup(jpanelRound2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtProductoS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(125, 125, 125))
                        .addGroup(jpanelRound2Layout.createSequentialGroup()
                            .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JcFechaS, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCantidadS, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(txtPrecioS)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGap(48, 48, 48)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound2Layout.createSequentialGroup()
                        .addComponent(btnNuevaSa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtStockS, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelRound2Layout.setVerticalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnNuevaSa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDEntradaS, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductoS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecioS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JcFechaS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtStockS))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        TablaS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idSalida", "idEntrada", "Producto", "PrecioU", "Cantidad", "Importe"
            }
        ));
        jScrollPane1.setViewportView(TablaS);

        jpanelRound3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setText("Subtotal");

        jLabel16.setText("Total");

        BtnGenerar.setBackground(new java.awt.Color(0, 102, 255));
        BtnGenerar.setText("Generar");
        BtnGenerar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        BtnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerarActionPerformed(evt);
            }
        });

        jLabel17.setText("Igv");

        BtnAgregarEntrada.setBackground(new java.awt.Color(0, 102, 255));
        BtnAgregarEntrada.setText("Agregar");
        BtnAgregarEntrada.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        BtnAgregarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelRound3Layout = new javax.swing.GroupLayout(jpanelRound3);
        jpanelRound3.setLayout(jpanelRound3Layout);
        jpanelRound3Layout.setHorizontalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addGroup(jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelRound3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpanelRound3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpanelRound3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnAgregarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jpanelRound3Layout.setVerticalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAgregarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        BtnBuscarEntrada.setText("Buscar");
        BtnBuscarEntrada.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        BtnBuscarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarEntradaActionPerformed(evt);
            }
        });

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        txtnumSa.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtnumSa.setText("spdfs");

        txtnSalida.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        txtnSalida.setText("Numero Salida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpanelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jpanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(325, 325, 325)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtnSalida)
                                .addGap(18, 18, 18)
                                .addComponent(txtnumSa)
                                .addGap(163, 163, 163)
                                .addComponent(BtnBuscarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(369, 369, 369)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(579, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnBuscarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnumSa)
                            .addComponent(txtnSalida))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpanelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jpanelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(588, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerarActionPerformed
      
         // TODO add your handling code here:
      s.setNumSalida(txtnumSa.getText());
      s.setIdCliente(Integer.parseInt(txtIDClienteS.getText()));
      s.setSubTotal(Double.parseDouble(txtSubtotal.getText()));
      s.setIgv(Double.parseDouble(txtIGV.getText()));
      s.setTotal(Double.parseDouble(txtTotal.getText()));
       Calendar cal;
        int d,m,a;
        cal=JcFechaS.getCalendar();
        d=cal.get(Calendar.DAY_OF_MONTH);
        m=cal.get(Calendar.MONTH);
        a=cal.get(Calendar.YEAR)-1900;
        s.setFecha(new Date(a,m,d));
        
       if(Cts.insertar(s)){
          // JOptionPane.showMessageDialog(null, "Registro de categoría completado");
          GuardarDetalle();
           MenuPrincipal me =new MenuPrincipal(); 
           me.exito("Salida regiistrada con exito");
           //limpiarCampos();
           //limpiarTablaClientes();
           //listarClientes();
           
       }else{
           MenuPrincipal me =new MenuPrincipal(); 
           me.warning("no se  pudo registrar al cliente ");
       }          
    }//GEN-LAST:event_BtnGenerarActionPerformed

    private void txtDocumentoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoSActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
            c.setDocumento(txtDocumentoS.getText());
            
             if (ctcl.buscar(c)) {
             txtIDClienteS.setText(c.getIdCliente() + "");
             txtNombreClienteS.setText(c.getNombre() + " " + c.getApellido());
             txtDocumentoS.setText(c.getDocumento());
             txtTelefonoS.setText(c.getTelefono());
             txtCorreoS.setText(c.getCorreo());
             } else {
              MenuPrincipal m = new MenuPrincipal();
              m.warning("El Cliente No Existe");
             // limpiarCampos();
             }  
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void txtTelefonoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoSActionPerformed

    private void BtnBuscarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarEntradaActionPerformed
        // TODO add your handling code here:
        BuscarProductos m = new BuscarProductos();
        m.setVisible(true);
        
    }//GEN-LAST:event_BtnBuscarEntradaActionPerformed

    private void BtnAgregarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarEntradaActionPerformed
        agregaEntrada();
        limpiarDatosProducto();
        sumarTotal();      
    }//GEN-LAST:event_BtnAgregarEntradaActionPerformed

    private void btnNuevaSaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaSaActionPerformed
        // TODO add your handling code here:
        numSalida();
        limpiarDatosProducto();
        LimpiarDatosCli();
        limpiarTablaSalidas();
    }//GEN-LAST:event_btnNuevaSaActionPerformed

    
    private void agregaEntrada(){
       double precio,total,importe; 
       modeloE = (DefaultTableModel) TablaS.getModel();
       int idEntrada=Integer.parseInt(txtIDEntradaS.getText());
       int idSalida=Integer.parseInt(txtnumSa.getText());
       int cantidad=Integer.parseInt(txtCantidadS.getText());
       precio = Double.parseDouble(txtPrecioS.getText());
       String prod = txtProductoS.getText();
       importe=cantidad*precio;
       int stock = Integer.parseInt(txtStockS.getText());
     ArrayList lista = new ArrayList();
if (stock > 0 && cantidad <= stock) {
    lista.add(idSalida);
    lista.add(idEntrada);
    lista.add(prod);
    lista.add(precio);
    lista.add(cantidad);
    lista.add(importe);

    Object[] ob = new Object[4];
    ob[0] = lista.get(0);
    ob[1] = lista.get(1);
    ob[2] = lista.get(2);
    ob[3] = lista.get(3);
    ob[4] = lista.get(4);
    ob[5] = lista.get(5);
    modeloE.addRow(ob);

    TablaS.setModel(modeloE);
} else {
    MenuPrincipal m = new MenuPrincipal();
    m.warning("Stock Insuficiente");
}
    } 

    void GuardarDetalle(){
        for(int i = 0; i<TablaS.getRowCount();i++){
        int idSalida = Integer.parseInt(TablaS.getValueAt(i, 0).toString());
        int idEntrada = Integer.parseInt(TablaS.getValueAt(i, 1).toString());
        int cant = Integer.parseInt(TablaS.getValueAt(i, 4).toString());  
        double importe = Double.parseDouble(TablaS.getValueAt(i, 5).toString());
        cdeta.insertar(idSalida, idEntrada, cant, importe);
        }
    }
   
    void sumarTotal(){
        double fila, igv, subtotal, total = 0;
        for (int i = 0; i < TablaS.getRowCount(); i++) {
        fila = Double.parseDouble(TablaS.getValueAt(i, 5).toString());
        total += fila;
        igv = total * 0.18;
        subtotal = total - igv;
        
        txtTotal.setText(String.format("4.2f", total).replace(",", "."));
        txtSubtotal.setText(String.format("4.2f", subtotal).replace(",", "."));
        txtIGV.setText(String.format("4.2f", igv).replace(",", "."));
        }  
    }
    
    void limpiarDatosProducto(){
        txtIDEntradaS.setText("");
        txtProductoS.setText("");
        txtStockS.setText("");
        txtPrecioS.setText("");
        txtCantidadS.setText("");   
    }
    
    void LimpiarDatosCli(){
        txtDocumentoS.setText("");
        txtCorreoS.setText("");
        txtIDClienteS.setText("");
        txtTelefonoS.setText("");
        txtNombreClienteS.setText(""); 
}
    
    void limpiarTablaSalidas(){
          for (int i = 0; i < modeloE.getRowCount(); i++) {
        modeloE.removeRow(i);
        i = i - 1;
       }
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconDos BtnAgregarEntrada;
    private RSMaterialComponent.RSButtonMaterialIconDos BtnBuscarEntrada;
    private RSMaterialComponent.RSButtonMaterialIconDos BtnGenerar;
    private com.toedter.calendar.JDateChooser JcFechaS;
    private javax.swing.JTable TablaS;
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscarCliente;
    private RSMaterialComponent.RSButtonMaterialIconDos btnNuevaSa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private modelo.JpanelRound jpanelRound1;
    private modelo.JpanelRound jpanelRound2;
    private modelo.JpanelRound jpanelRound3;
    private javax.swing.JTextField txtCantidadS;
    private javax.swing.JTextField txtCorreoS;
    private javax.swing.JTextField txtDocumentoS;
    private javax.swing.JTextField txtIDClienteS;
    public static javax.swing.JTextField txtIDEntradaS;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtNombreClienteS;
    public static javax.swing.JTextField txtPrecioS;
    public static javax.swing.JTextField txtProductoS;
    public static javax.swing.JTextField txtStockS;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTelefonoS;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JLabel txtnSalida;
    private javax.swing.JLabel txtnumSa;
    // End of variables declaration//GEN-END:variables
}
