/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;


import controlador.DaoUsuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.usuarios;

/**
 *
 * @author User
 */
public class Usuarios extends javax.swing.JPanel {
    
    
  DaoUsuario cu=new DaoUsuario();
   usuarios u = new usuarios();
   DefaultTableModel modeloU =new DefaultTableModel();
    /**
     * Creates new form usuarios
     */
    public Usuarios() {
        initComponents();
        listarUsuarios();
    }

     private void listarUsuarios() {
 List<usuarios> listaUsuario = cu.listarUsuario();
modeloU = (DefaultTableModel) TableU.getModel();
Object[] ob = new Object[9];  

for (int i = 0; i < listaUsuario.size(); i++) {
    
        ob[0] = listaUsuario.get(i).getIdusuario();
        ob[1] = listaUsuario.get(i).getNombre();
        ob[2] = listaUsuario.get(i).getApellido();
        ob[3] = listaUsuario.get(i).getDocumento();
        ob[4] = listaUsuario.get(i).getTelefono();
        ob[5] = listaUsuario.get(i).getCorreo();
        ob[6] = listaUsuario.get(i).getTipoUsuario();
        ob[7] = listaUsuario.get(i).getUsuario();
        ob[8] = listaUsuario.get(i).getPassword();

    
    modeloU.addRow(ob);
   }
}
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jpanelRound1 = new modelo.JpanelRound();
        jLabel2 = new javax.swing.JLabel();
        txtIDU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombreU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoU = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDocumentoU = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefonoU = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        txtCorreoU = new javax.swing.JTextField();
        tipoUsuario = new javax.swing.JLabel();
        comboUsuario = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtusuarioU = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcontraseñaU = new javax.swing.JTextField();
        btnGuardarU = new RSMaterialComponent.RSButtonMaterialIconDos();
        jpanelRound2 = new modelo.JpanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableU = new javax.swing.JTable();
        btnEliminarU = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnBuscarU = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEditarU = new RSMaterialComponent.RSButtonMaterialIconDos();

        setMaximumSize(new java.awt.Dimension(32787, 32787));
        setPreferredSize(new java.awt.Dimension(902, 690));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel1.setText("Registro de Usuarios");

        jpanelRound1.setBackground(new java.awt.Color(255, 255, 255));
        jpanelRound1.setRoundBottomLeft(25);
        jpanelRound1.setRoundBottomRight(25);
        jpanelRound1.setRoundTopLeft(25);
        jpanelRound1.setRoundTopRight(25);

        jLabel2.setText("ID");

        txtIDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDUActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre");

        txtNombreU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUActionPerformed(evt);
            }
        });

        jLabel4.setText("Apellido");

        jLabel5.setText("Documento");

        txtDocumentoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoUActionPerformed(evt);
            }
        });

        jLabel7.setText("Telefono");

        Correo.setText("Correo");

        tipoUsuario.setText("TipoUsuario");

        comboUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador" }));

        jLabel8.setText("Usuario");

        txtusuarioU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioUActionPerformed(evt);
            }
        });

        jLabel9.setText("contraseña");

        txtcontraseñaU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraseñaUActionPerformed(evt);
            }
        });

        btnGuardarU.setBackground(new java.awt.Color(255, 0, 0));
        btnGuardarU.setText("Guardar");
        btnGuardarU.setBackgroundHover(new java.awt.Color(255, 255, 255));
        btnGuardarU.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelRound1Layout = new javax.swing.GroupLayout(jpanelRound1);
        jpanelRound1.setLayout(jpanelRound1Layout);
        jpanelRound1Layout.setHorizontalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Correo)
                        .addGap(122, 122, 122))
                    .addGroup(jpanelRound1Layout.createSequentialGroup()
                        .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addGroup(jpanelRound1Layout.createSequentialGroup()
                                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtIDU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                        .addComponent(txtNombreU, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtApellidoU, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDocumentoU, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTelefonoU, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(tipoUsuario)
                                    .addComponent(txtCorreoU, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtusuarioU, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(txtcontraseñaU, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnGuardarU, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        jpanelRound1Layout.setVerticalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Correo))
                .addGap(12, 12, 12)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tipoUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreU, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtusuarioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelRound1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9))
                    .addGroup(jpanelRound1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addGap(15, 15, 15)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocumentoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcontraseñaU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jpanelRound2.setBackground(new java.awt.Color(255, 255, 255));

        TableU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Documento", "Telefono", "Correo", "Tipo de usuario", "Usuario", "Contraseña"
            }
        ));
        TableU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableU);

        javax.swing.GroupLayout jpanelRound2Layout = new javax.swing.GroupLayout(jpanelRound2);
        jpanelRound2.setLayout(jpanelRound2Layout);
        jpanelRound2Layout.setHorizontalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jpanelRound2Layout.setVerticalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnEliminarU.setBackground(new java.awt.Color(51, 102, 255));
        btnEliminarU.setText("Eliminar");
        btnEliminarU.setBackgroundHover(new java.awt.Color(255, 255, 255));
        btnEliminarU.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnEliminarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUActionPerformed(evt);
            }
        });

        btnBuscarU.setBackground(new java.awt.Color(51, 102, 255));
        btnBuscarU.setText("Buscar");
        btnBuscarU.setBackgroundHover(new java.awt.Color(255, 255, 255));
        btnBuscarU.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        btnBuscarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUActionPerformed(evt);
            }
        });

        btnEditarU.setBackground(new java.awt.Color(51, 102, 255));
        btnEditarU.setText("Editar");
        btnEditarU.setBackgroundHover(new java.awt.Color(255, 255, 255));
        btnEditarU.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnEditarU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnEditarU, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarU, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarU, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jpanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditarU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUActionPerformed

    private void txtDocumentoUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoUActionPerformed

    private void btnGuardarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUActionPerformed

        // TODO add your handling code here:
        u.setNombre(txtNombreU.getText());
        u.setApellido(txtApellidoU.getText());
        u.setDocumento(txtDocumentoU.getText());
        u.setTelefono(txtTelefonoU.getText());
        u.setCorreo(txtCorreoU.getText());
        u.setTipoUsuario(comboUsuario.getSelectedItem().toString());
        u.setUsuario(txtusuarioU.getText());
        u.setPassword(txtcontraseñaU.getText());
            if (cu.insertar(u.getNombre(), u.getApellido(), u.getDocumento(),
                u.getTelefono(), u.getCorreo(), u.getTipoUsuario(), 
                 u.getUsuario(), u.getPassword())) {
            // JOptionPane.showMessageDialog(null, "Registro de categoría completado");
            MenuPrincipal me =new MenuPrincipal();
            me.exito("cliente registrado con exito");
            limpiarCampos();
           limpiarTablaUsuario();
            listarUsuarios();

        }else{
            MenuPrincipal me =new MenuPrincipal();
            me.warning("no se  pudo registrar al cliente ");
        }
    }//GEN-LAST:event_btnGuardarUActionPerformed

    private void btnEliminarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUActionPerformed
        // TODO add your handling code here:
        if (!txtIDU.getText().isEmpty()) {
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿De verdad Estas seguro de eliminar el usuario?", "Confirmar", 2);
        if (confirmacion == 0) {           
            u.setIdusuario(Integer.parseInt(txtIDU.getText()));
            cu.eliminar(u);
            limpiarTablaUsuario();
            listarUsuarios();
            limpiarTablaUsuario();
            //JOptionPane.showMessageDialog(null, "Se elimino con exito el cliente");
             MenuPrincipal me =new MenuPrincipal(); 
             me.exito("Se elimino con exito");
         }
      }else{
          MenuPrincipal me =new MenuPrincipal(); 
          me.warning("Seleccione un usuario");
        }
        
    }//GEN-LAST:event_btnEliminarUActionPerformed

    private void btnBuscarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUActionPerformed
        // TODO add your handling code here:
         
              u.setDocumento(txtDocumentoU.getText());
              if (cu.buscar(u)){
                txtIDU.setText(u.getIdusuario() + "");
                txtNombreU.setText(u.getNombre());
                txtApellidoU.setText(u.getApellido());
                txtDocumentoU.setText(u.getDocumento());
                txtTelefonoU.setText(u.getTelefono());
                txtCorreoU.setText(u.getCorreo());
                txtusuarioU.setText(u.getUsuario());
                txtcontraseñaU.setText(u.getPassword());
                comboUsuario.setSelectedItem(u.getTipoUsuario());
                
            } else {
              MenuPrincipal me =new MenuPrincipal(); 
              me.warning("El usuario no existe"); 
              limpiarCampos();
             }
        
    }//GEN-LAST:event_btnBuscarUActionPerformed

    private void btnEditarUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUActionPerformed
        // TODO add your handling code here:
        int fila = TableU.getSelectedRow();
        if (fila == -1 || txtIDU.getText().isEmpty()) {
         
            MenuPrincipal m = new MenuPrincipal();
                m.warning("Seleccione un usuario");
         }else{
            u.setIdusuario(Integer.parseInt(txtIDU.getText()));
            u.setNombre(txtNombreU.getText());
            u.setApellido(txtApellidoU.getText());
            u.setDocumento(txtDocumentoU.getText());
            u.setTelefono(txtTelefonoU.getText());
            u.setCorreo(txtCorreoU.getText());
            u.setTipoUsuario(comboUsuario.getSelectedItem().toString());
            u.setUsuario(txtusuarioU.getText());
            u.setPassword(txtcontraseñaU.getText());
             if (cu.editar(u.getNombre(), u.getApellido(), u.getDocumento(),
               u.getTelefono(), u.getCorreo(), u.getTipoUsuario(), 
               u.getUsuario(), u.getPassword(), u.getIdusuario())){
                 
             //JOptionPane.showMessageDialog(null,"se modifico con exito");
              MenuPrincipal me =new MenuPrincipal(); 
              me.exito("modificado con exito");
             limpiarCampos();
             //limpiarTablaProveedor();
             //listarProveedores();
             }else{
              MenuPrincipal me =new MenuPrincipal(); 
              me.warning("Error al modificar el usuario"); 
             }
         }
    }//GEN-LAST:event_btnEditarUActionPerformed

    private void txtusuarioUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioUActionPerformed

    private void txtcontraseñaUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraseñaUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseñaUActionPerformed

    private void txtIDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDUActionPerformed

    private void TableUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUMouseClicked
        // TODO add your handling code here:
        int fila = TableU.getSelectedRow();
        txtIDU.setText(TableU.getValueAt(fila, 0).toString());
        txtNombreU.setText(TableU.getValueAt(fila, 1).toString());
        txtApellidoU.setText(TableU.getValueAt(fila, 2).toString());
        txtDocumentoU.setText(TableU.getValueAt(fila, 3).toString());
        txtTelefonoU.setText(TableU.getValueAt(fila, 4).toString());
        txtCorreoU.setText(TableU.getValueAt(fila, 5).toString()); 
        comboUsuario.setSelectedItem(TableU.getValueAt(fila, 6).toString());
        txtusuarioU.setText(TableU.getValueAt(fila, 7).toString()); 
        
        u.setDocumento(txtDocumentoU.getText());
         if (cu.buscar(u)){
             txtcontraseñaU.setText(u.getPassword());
         }
    }//GEN-LAST:event_TableUMouseClicked


    
     void limpiarCampos(){
     txtIDU.setText("");
     txtNombreU.setText("");
     txtApellidoU.setText("");
     txtDocumentoU.setText("");
     txtTelefonoU.setText("");
     txtCorreoU.setText("");
     txtusuarioU.setText("");
     txtcontraseñaU.setText("");
 }

  void limpiarTablaUsuario(){
          for (int i = 0; i < modeloU.getRowCount(); i++) {
        modeloU.removeRow(i);
        i = i - 1;
       }
     }
             
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Correo;
    private javax.swing.JTable TableU;
    private RSMaterialComponent.RSButtonMaterialIconDos btnBuscarU;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEditarU;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEliminarU;
    private RSMaterialComponent.RSButtonMaterialIconDos btnGuardarU;
    private javax.swing.JComboBox<String> comboUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private modelo.JpanelRound jpanelRound1;
    private modelo.JpanelRound jpanelRound2;
    private javax.swing.JLabel tipoUsuario;
    private javax.swing.JTextField txtApellidoU;
    private javax.swing.JTextField txtCorreoU;
    private javax.swing.JTextField txtDocumentoU;
    private javax.swing.JTextField txtIDU;
    private javax.swing.JTextField txtNombreU;
    private javax.swing.JTextField txtTelefonoU;
    private javax.swing.JTextField txtcontraseñaU;
    private javax.swing.JTextField txtusuarioU;
    // End of variables declaration//GEN-END:variables
}
